format = """
$username\
$hostname\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$golang\
$java\
$kotlin\
$nodejs\
$python\
$rust\
$env_var\
$custom\
$cmd_duration\
$line_break\
$status\
$shell\
$character"""


add_newline = false

[gcloud]
disabled = true

[username]
show_always = true
format = " [$user]($style)@"
style_user = "bold blue"

[hostname]
ssh_only = false
format = "[$hostname]($style) in "
style = "bold cyan"

[character]
success_symbol = "[❯](bold blue)"



[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "

