#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config window_gap             0
bspc config split_ratio            0

bspc config borderless_monocle     true
bspc config single_monocle         true

bspc config active_border_color \#3498db
bspc config normal_border_color \#000
bspc config focused_border_color \#3498db
bspc config border_width 1

bspc rule -a Alacritty desktop='^1'
bspc rule -a firefoxdeveloperedition desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a "Code - Insiders" desktop='^4'
bspc rule -a Brave-browser desktop='^4'
bspc rule -a MultiMC5 state=floating
bspc rule -a zoom state=floating follow=on desktop='^8'
bspc rule -a Peek state=floating
bspc rule -a Pavucontrol state=floating

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
